services:
  app:
    container_name: php.umarket
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  python:
    container_name: python.umarket
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
